# Generated by Django 3.1.14 on 2025-02-11 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='Название (en)')),
                ('title_jp', models.CharField(blank=True, max_length=200, verbose_name='Название (jp)')),
                ('photo', models.ImageField(null=True, upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('previous_evolution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_evolution', to='pokemon_entities.pokemon', verbose_name='Предыдущая эволюция')),
            ],
        ),
        migrations.CreateModel(
            name='PokemonEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(null=True, verbose_name='Широта')),
                ('lon', models.FloatField(null=True, verbose_name='Долгота')),
                ('appeared_at', models.DateTimeField(null=True, verbose_name='Дата появления')),
                ('disappeared_at', models.DateTimeField(null=True, verbose_name='Дата исчезновения')),
                ('level', models.IntegerField(null=True, verbose_name='Уровень')),
                ('health', models.IntegerField(null=True, verbose_name='Здоровье')),
                ('defence', models.IntegerField(null=True, verbose_name='Защита')),
                ('stamina', models.IntegerField(null=True, verbose_name='Выносливость')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity', to='pokemon_entities.pokemon', verbose_name='Покемон')),
            ],
        ),
    ]
